import 'package:hugeicons/hugeicons.dart';

List iconsList = [
  HugeIcons.strokeRoundedBank,
  HugeIcons.strokeRoundedPiggyBank,
  HugeIcons.strokeRoundedHospital02,
  HugeIcons.strokeRoundedFirstAidKit,
  HugeIcons.strokeRoundedCargoShip,
  HugeIcons.strokeRoundedCar01,
  HugeIcons.strokeRoundedBus01,
  HugeIcons.strokeRoundedSpeedTrain01,
  HugeIcons.strokeRoundedAirplaneTakeOff01,
  HugeIcons.strokeRoundedCoffee01,
  HugeIcons.strokeRoundedBooks02,
  HugeIcons.strokeRoundedFrenchFries02,
  HugeIcons.strokeRoundedMotorbike02,
  HugeIcons.strokeRoundedCharity,
  HugeIcons.strokeRoundedTaxi02,
  HugeIcons.strokeRoundedVegetarianFood,
  HugeIcons.strokeRoundedYoutube,
  HugeIcons.strokeRoundedSmartPhone01,
  HugeIcons.strokeRoundedInternet,
  HugeIcons.strokeRoundedUser,
  HugeIcons.strokeRoundedShoppingBag01,
  HugeIcons.strokeRoundedPrinter,
  HugeIcons.strokeRoundedDribbble,
  HugeIcons.strokeRoundedMail01,
  HugeIcons.strokeRoundedAutomotiveBattery02,
  HugeIcons.strokeRoundedSparkles,
  HugeIcons.strokeRoundedMore02,
];
